7 add marathons page
Sztab-WOSP-Bialystok/wosp-staff pull request #14
Opened 2024-01-02 20:27 UTC by TheUnDc

2024-01-03 19:55 UTC, Freesebee requested changes
❤️ but I will add placeholder data, and consult layout with coordinator

2024-01-03 19:55 UTC, Freesebee commented on app/concerts/page.tsx
> +		<Row>
```suggestion
```

2024-01-03 19:55 UTC, Freesebee commented on app/concerts/page.tsx
> +		</Row>
```suggestion
```

2024-01-03 19:55 UTC, Freesebee commented on app/marathons/page.tsx
> +			<Col xl={{ span: 8, offset: 2 }} className="my-3 img-overlay">
```suggestion
                        <Row>
			                  <Col xl={{ span: 8, offset: 2 }} className="my-3 img-overlay">
```

2024-01-03 19:55 UTC, Freesebee commented on app/marathons/page.tsx
> +			<Row>
```suggestion
```

2024-01-08 19:48 UTC, Freesebee requested changes
🤗 🎖️

2024-01-08 19:48 UTC, Freesebee commented on app/components/navbar/navigation.ts
> +  CONCERTS = "/concerts",
```suggestion
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +						Biegnij dla zdrowia i zabawy! Dołącz do tysięcy biegaczy
When making responsive UI design it's important to remember polish grammar rules. [As a general rule, you should not leave single-letter conjunctions and prepositions at the end of a line](https://sjp.pwn.pl/poradnia/haslo/Sieroty-na-koncu-wiersza;18684.html#:~:text=W%20wierszach%20tekstu%2C%20kt%C3%B3re%20licz%C4%85%20powy%C5%BCej%2040%20znak%C3%B3w%2C,dopuszczalne%20tylko%20przy%20bardzo%20w%C4%85skim%20%C5%82amie%20%28np.%20gazetowym%29.)

You can achievie this by using non-breaking space `&nbsp;`

```suggestion
						Biegnij dla zdrowia i&nbsp;zabawy! Dołącz do tysięcy biegaczy
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +	const marathonExternal = externalSourceData.find(
As I learned from @Kompanel 😄 - use states to reduce calling `find()` method
```suggestion
	const [marathonExternal ] = useState<ExteralSource>(externalSourceData.find((x) => x.key ==EXTERNAL_SOURCE_KEYS.BIALYSTOK_WEB)
```

**Remember to import useState and other types like in [Honorary Patronage page](https://github.com/Sztab-WOSP-Bialystok/wosp-staff/tree/main/app/home/sections/honorary-patriage)**

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +										Wybrać odpowiednią opcję w zależności od
```suggestion
										Wybrać odpowiednią opcję w&nbsp;zależności od
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +										sprawdzamy formularze i odpisujemy
```suggestion
										sprawdzamy formularze i&nbsp;odpisujemy
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +									Nie czekaj, zarejestruj się i biegnij z
```suggestion
									Nie czekaj, zarejestruj się i&nbsp;biegnij z&nbsp;
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
> +									Wejdź w formularz i wypełnij (UWAGA:
```suggestion
									Wejdź w formularz i&nbsp;wypełnij (UWAGA:
```

2024-01-08 19:48 UTC, Freesebee commented on app/marathons/page.tsx
From upper staff: 
- remove all accordion, listGroup components: <img width="530" alt="image" src="https://github.com/Sztab-WOSP-Bialystok/wosp-staff/assets/63885889/eac13d0c-04e0-489c-977e-032ccdaac1de">
- remo space between cards: <img width="658" alt="image" src="https://github.com/Sztab-WOSP-Bialystok/wosp-staff/assets/63885889/1c4a06fb-ce99-49ee-84c6-53aa8a30c8ee">
- remove "Uranium-235" styling from second card to match cards in other pages: <img width="344" alt="image" src="https://github.com/Sztab-WOSP-Bialystok/wosp-staff/assets/63885889/f0d09d5a-a4c3-4fc0-a343-2692b19974cf">

2024-01-09 11:26 UTC, Kompanel approved these changes

2024-01-09 18:50 UTC, TheUnDc commented on app/marathons/page.tsx
done

2024-01-09 22:22 UTC, Freesebee approved these changes
❤️

2024-01-09 23:14 UTC, merged