Sztab-WOSP-Bialystok/wosp-staff#11
Sztab-WOSP-Bialystok/wosp-staff pull request #15
Opened 2024-01-02 21:14 UTC by TheUnDc

2024-01-03 19:48 UTC, Freesebee commented on app/concerts/page.tsx
> +		</Row>
```suggestion
```

2024-01-08 20:31 UTC, Freesebee requested changes
🏅 🔥

2024-01-08 20:31 UTC, Freesebee commented on app/concerts/concerts/current/current-data.json
File can be deleted - concerts poster will be used

2024-01-08 20:31 UTC, Freesebee commented on app/concerts/concerts/current/current.tsx
File can be deleted - concerts poster will be used

2024-01-08 20:31 UTC, Freesebee commented on app/concerts/page.tsx
> +						<Current></Current>
I added concerts poster image in branch [11-concerts-page](https://github.com/Sztab-WOSP-Bialystok/wosp-staff/tree/11-concerts-page). Scale it down to match page main Container component and upload like in [Honorary Patronage](https://github.com/Sztab-WOSP-Bialystok/wosp-staff/blob/11-concerts-page/app/home/sections/honorary-patriage/honorary-patronage-section.tsx)
```suggestion
						<img src={concertsPoster.src} width={"100%"} />
```

2024-01-09 11:27 UTC, Kompanel approved these changes

2024-01-09 19:23 UTC, TheUnDc commented on app/concerts/concerts/current/current-data.json
done

2024-01-09 19:23 UTC, TheUnDc commented on app/concerts/concerts/current/current.tsx
done

2024-01-10 00:02 UTC, Freesebee approved these changes
❤️

2024-01-10 00:02 UTC, merged